server:
  forward-headers-strategy: framework

spring:
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

application:
  security:
    email-verification:
      log-generated-token: ${EMAIL_VERIFICATION_LOG_GENERATED_TOKEN:false}
  seed:
    demo-data-enabled: ${DEMO_DATA_ENABLED:false}
